Moved database parameters from build to deploy

diff --git a/.openshift/action_hooks/deploy b/.openshift/action_hooks/deploy
--- a/.openshift/action_hooks/deploy
+++ b/.openshift/action_hooks/deploy
@@ -13,15 +13,20 @@ if [ -z $OPENSHIFT_DB_HOST ]
 then
     echo 1>&2
     echo 1>&2
-    echo "Could not find mysql database.  Please run:" 1>&2
-    echo "rhc-ctl-app -a $OPENSHIFT_APP_NAME -e add-mysql-5.1" 1>&2
-    echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
+    echo "Could not find postgresql database.  Please run:" 1>&2
+    echo "rhc-ctl-app -a $OPENSHIFT_APP_NAME -e add-postgresql-9.2" 1>&2
     echo 1>&2
     echo 1>&2
     exit 5
 fi
 
 cd $OPENSHIFT_REPO_DIR/wsgi/$APP
+
+sed -i 's/^db.host=.*/db.host='$OPENSHIFT_POSTGRESQL_DB_HOST'/' production.ini
+sed -i 's/^db.port=.*/db.port='$OPENSHIFT_POSTGRESQL_DB_PORT'/' production.ini
+sed -i 's/^db.dbname=.*/db.dbname='$OPENSHIFT_APP_NAME '/' production.ini
+sed -i 's/^db.username=.*/db.user='$OPENSHIFT_POSTGRESQL_DB_USERNAME'/' production.ini
+sed -i 's/^db.password=.*/db.password='$OPENSHIFT_POSTGRESQL_DB_PASSWORD'/' production.ini
 
 # Initialize our database
 if [ ! -e $OPENSHIFT_DATA_DIR/DB_INITIALIZED ]; then
